export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  MISSION: "/mission",
  HOW_IT_WORKS: "/how-it-works",
  FAQ: "/faq",
  REFUNDS: "/refunds",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ACTIVATE_ACCOUNT: "/account-validation",
  PROFILE: "/profile",
  CHECKOUT: (id: string | number = ":id") => `/deals/${id}/checkout`,
  SUCCESS_SUBSCRIPTION: (id: string | number = ":id") =>
    `/subscription/${id}/success`,
  DEAL_DETAIL: (id: string | number = ":id") => `/deals/${id}`,
  ORDERS: "/orders",
  FAVORITES: "/profile#favorites",
  SEARCH: "/search",
  USERSITTINGS: "/profile#settings",
  CATEGORIES: (id: string | number = ":id") => `/categories/${id}`,
  ALL_CATEGORIES: "/categories",
  TERMS: "/terms-of-use",
  PRIVACY: "/privacy-policy",
  COOKIES: "/cookies",
  LEGAL_NOTICE: "/legal-notice",
  BECOME_SELLER: "/become-a-seller",
  SELLER_TERMS: "/seller-terms",
  SUPPLIER_CHARTER: "/supplier-charter",
  NOT_FOUND: "/404",
  DEALS: "/deals",
  ADMIN: "/admin",
};
