import { Clock, Shield, TrendingDown, Users } from "lucide-react";

export const mockDeals = [
  {
    id: 1,
    title: "Massage Premium Spa",
    image: "https://picsum.photos/200",
    originalPrice: 150,
    groupPrice: 75,
    unit: "séance",
    sold: 42,
    total: 100,
    deadline: "15 jours",
    category: "wellness",
    city: "Paris",
    discount: 50,
  },
  {
    id: 2,
    title: "Restaurant Gastronomique",
    image: "https://picsum.photos/700",
    originalPrice: 85,
    groupPrice: 49,
    unit: "menu",
    sold: 78,
    total: 150,
    deadline: "8 jours",
    category: "food",
    city: "Lyon",
    discount: 42,
  },
  {
    id: 3,
    title: "Cours de Yoga",
    image: "https://picsum.photos/600",
    originalPrice: 40,
    groupPrice: 24,
    unit: "mois",
    sold: 25,
    total: 50,
    deadline: "22 jours",
    category: "wellness",
    city: "Marseille",
    discount: 40,
  },
  {
    id: 4,
    title: "Gadgets Tech Premium",
    image: "https://picsum.photos/500",
    originalPrice: 199,
    groupPrice: 129,
    unit: "unité",
    sold: 156,
    total: 200,
    deadline: "5 jours",
    category: "tech",
    city: "Paris",
    discount: 35,
  },
  {
    id: 5,
    title: "Formation Digital Marketing",
    image: "https://picsum.photos/300",
    originalPrice: 299,
    groupPrice: 149,
    unit: "cours",
    sold: 33,
    total: 100,
    deadline: "18 jours",
    category: "education",
    city: "Toulouse",
    discount: 50,
  },
  {
    id: 6,
    title: "Accessoires Fashion",
    image: "https://picsum.photos/400",
    originalPrice: 120,
    groupPrice: 59,
    unit: "article",
    sold: 89,
    total: 120,
    deadline: "12 jours",
    category: "fashion",
    city: "Bordeaux",
    discount: 51,
  },
];

export const features = [
  {
    icon: Users,
    title: "Force du Groupe",
    description: "Plus vous êtes nombreux, plus la réduction est importante",
  },
  {
    icon: TrendingDown,
    title: "Économies Garanties",
    description: "Jusqu'à 70% de réduction sur les meilleurs deals",
  },
  {
    icon: Clock,
    title: "Délais Courts",
    description:
      "Les deals disparaissent rapidement. Saisissez l'opportunité !",
  },
  {
    icon: Shield,
    title: "Sécurisé",
    description: "Paiement sécurisé et garantie de satisfaction client",
  },
];

export const slides = [
  {
    id: 1,
    title: "Découvrez les Meilleurs Deals",
    subtitle: "Jusqu'à 70% de réduction",
    description:
      "Restaurants, spa, activités et bien plus encore dans votre ville",
    buttonText: "Explorer maintenant",
    buttonLink: "/deals",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    gradient: "from-purple-600/50 to-pink-600/50",
    textColor: "text-white",
    badge: "Nouveauté",
  },
  {
    id: 2,
    title: "Bien-être & Détente",
    subtitle: "Offres exclusives Spa",
    description:
      "Profitez d'un moment de relaxation avec nos offres spa et massage",
    buttonText: "Voir les offres spa",
    buttonLink: "/deals/spa",
    image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80",
    gradient: "from-teal-600/50 to-cyan-600/50",
    textColor: "text-white",
    badge: "Populaire",
  },
  {
    id: 3,
    title: "Saveurs Gastronomiques",
    subtitle: "Restaurants étoilés à prix réduits",
    description:
      "Découvrez les meilleurs restaurants de votre ville à des prix imbattables",
    buttonText: "Réserver une table",
    buttonLink: "/deals/restaurants",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    gradient: "from-orange-600/50 to-red-600/50",
    textColor: "text-white",
    badge: "Tendance",
  },
  {
    id: 4,
    title: "Activités & Loisirs",
    subtitle: "Vivez des expériences uniques",
    description:
      "Sport, culture, aventure... Trouvez l'activité qui vous correspond",
    buttonText: "Découvrir les activités",
    buttonLink: "/deals/activities",
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&q=80",
    gradient: "from-blue-600/50 to-indigo-600/50",
    textColor: "text-white",
    badge: "Aventure",
  },
];
