import {
  Clock,
  Shield,
  TrendingDown,
  Users,
  Utensils,
  Sparkles,
  Dumbbell,
  Gift,
  ShoppingBag,
  Hotel,
  Car,
  HeartPulse,
  Plane,
  Camera,
  PawPrint,
  Hammer,
  GraduationCap,
  Music,
  Baby,
  Trees,
  Cpu,
} from "lucide-react";

export const mockDeals = [
  {
    id: 1,
    title: "Massage Premium Spa",
    image: "https://picsum.photos/200",
    originalPrice: 150,
    groupPrice: 75,
    unit: "séance",
    sold: 42,
    total: 100,
    deadline: "15 jours",
    category: "wellness",
    city: "Paris",
    discount: 50,
  },
  {
    id: 2,
    title: "Restaurant Gastronomique",
    image: "https://picsum.photos/700",
    originalPrice: 85,
    groupPrice: 49,
    unit: "menu",
    sold: 78,
    total: 150,
    deadline: "8 jours",
    category: "food",
    city: "Lyon",
    discount: 42,
  },
  {
    id: 3,
    title: "Cours de Yoga",
    image: "https://picsum.photos/600",
    originalPrice: 40,
    groupPrice: 24,
    unit: "mois",
    sold: 25,
    total: 50,
    deadline: "22 jours",
    category: "wellness",
    city: "Marseille",
    discount: 40,
  },
  {
    id: 4,
    title: "Gadgets Tech Premium",
    image: "https://picsum.photos/500",
    originalPrice: 199,
    groupPrice: 129,
    unit: "unité",
    sold: 156,
    total: 200,
    deadline: "5 jours",
    category: "tech",
    city: "Paris",
    discount: 35,
  },
  {
    id: 5,
    title: "Formation Digital Marketing",
    image: "https://picsum.photos/300",
    originalPrice: 299,
    groupPrice: 149,
    unit: "cours",
    sold: 33,
    total: 100,
    deadline: "18 jours",
    category: "education",
    city: "Toulouse",
    discount: 50,
  },
  {
    id: 6,
    title: "Accessoires Fashion",
    image: "https://picsum.photos/400",
    originalPrice: 120,
    groupPrice: 59,
    unit: "article",
    sold: 89,
    total: 120,
    deadline: "12 jours",
    category: "fashion",
    city: "Bordeaux",
    discount: 51,
  },
];

export const features = [
  {
    icon: Users,
    title: "Force du Groupe",
    description: "Plus vous êtes nombreux, plus la réduction est importante",
  },
  {
    icon: TrendingDown,
    title: "Économies Garanties",
    description: "Jusqu'à 70% de réduction sur les meilleurs deals",
  },
  {
    icon: Clock,
    title: "Délais Courts",
    description:
      "Les deals disparaissent rapidement. Saisissez l'opportunité !",
  },
  {
    icon: Shield,
    title: "Sécurisé",
    description: "Paiement sécurisé et garantie de satisfaction client",
  },
];

export const slides = [
  {
    id: 1,
    title: "Découvrez les Meilleurs Deals",
    subtitle: "Jusqu'à 70% de réduction",
    description:
      "Restaurants, spa, activités et bien plus encore dans votre ville",
    buttonText: "Explorer maintenant",
    buttonLink: "/deals",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    gradient: "from-purple-600/50 to-pink-600/50",
    textColor: "text-white",
    badge: "Nouveauté",
  },
  {
    id: 2,
    title: "Bien-être & Détente",
    subtitle: "Offres exclusives Spa",
    description:
      "Profitez d'un moment de relaxation avec nos offres spa et massage",
    buttonText: "Voir les offres spa",
    buttonLink: "/deals/spa",
    image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80",
    gradient: "from-teal-600/50 to-cyan-600/50",
    textColor: "text-white",
    badge: "Populaire",
  },
  {
    id: 3,
    title: "Saveurs Gastronomiques",
    subtitle: "Restaurants étoilés à prix réduits",
    description:
      "Découvrez les meilleurs restaurants de votre ville à des prix imbattables",
    buttonText: "Réserver une table",
    buttonLink: "/deals/restaurants",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    gradient: "from-orange-600/50 to-red-600/50",
    textColor: "text-white",
    badge: "Tendance",
  },
  {
    id: 4,
    title: "Activités & Loisirs",
    subtitle: "Vivez des expériences uniques",
    description:
      "Sport, culture, aventure... Trouvez l'activité qui vous correspond",
    buttonText: "Découvrir les activités",
    buttonLink: "/deals/activities",
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&q=80",
    gradient: "from-blue-600/50 to-indigo-600/50",
    textColor: "text-white",
    badge: "Aventure",
  },
];

export const categories = [
  {
    id: 1,
    name: "Restaurants",
    icon: Utensils,
    href: "restaurants",
    description:
      "Découvrez des offres exclusives sur les meilleurs restaurants près de chez vous.",
    count: 124,
    image:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1200",
    subcategories: ["Cuisine africaine", "Fast-food", "Desserts", "Buffets"],
  },
  {
    id: 2,
    name: "Beauté & Spa",
    icon: Sparkles,
    href: "beauty",
    description:
      "Soins du visage, massages, mise en beauté et autres expériences bien-être.",
    count: 89,
    image:
      "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?q=80&w=1200",
    subcategories: ["Massages", "Coiffure", "Soins du visage", "Manicure"],
  },
  {
    id: 3,
    name: "Sport & Fitness",
    icon: Dumbbell,
    href: "fitness",
    description:
      "Séances de sport, abonnements à des salles et activités de remise en forme.",
    count: 56,
    image:
      "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?q=80&w=1200",
    subcategories: ["Gym", "Yoga", "Électrostimulation", "Boxe"],
  },
  {
    id: 4,
    name: "Cadeaux",
    icon: Gift,
    href: "gifts",
    description: "Des idées cadeaux originales pour toutes les occasions.",
    count: 43,
    image:
      "https://images.unsplash.com/photo-1607082349566-18782b1d4852?q=80&w=1200",
    subcategories: [
      "Anniversaires",
      "Couples",
      "Événements",
      "Produits personnalisés",
    ],
  },
  {
    id: 5,
    name: "Shopping",
    icon: ShoppingBag,
    href: "shopping",
    description: "Mode, accessoires, appareils et autres bons plans shopping.",
    count: 210,
    image:
      "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?q=80&w=1200",
    subcategories: ["Mode femme", "Mode homme", "Électronique", "Accessoires"],
  },
  {
    id: 6,
    name: "Hôtels & Séjours",
    icon: Hotel,
    href: "hotels",
    description: "Nuits d'hôtel, séjours, escapades et voyages en promotion.",
    count: 32,
    image:
      "https://images.unsplash.com/photo-1501117716987-c8e1ecb21078?q=80&w=1200",
    subcategories: ["Weekend", "Séjours luxe", "Voyages", "Vacances"],
  },
  {
    id: 7,
    name: "Automobile",
    icon: Car,
    href: "auto",
    description: "Entretien automobile, lavage, réparations et accessoires.",
    count: 64,
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200",
    subcategories: ["Lavage", "Vidange", "Accessoires", "Réparation"],
  },
  {
    id: 8,
    name: "Santé & Bien-être",
    icon: HeartPulse,
    href: "health",
    description: "Consultations, soins médicaux et produits de santé.",
    count: 28,
    image:
      "https://images.unsplash.com/photo-1580281657527-47d715b1a19f?q=80&w=1200",
    subcategories: ["Nutrition", "Optique", "Consultations", "Fitness santé"],
  },
  {
    id: 9,
    name: "Voyages & Loisirs",
    icon: Plane,
    href: "travel",
    description: "Billets, activités touristiques, parcs et loisirs.",
    count: 44,
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200",
    subcategories: ["Activités", "Billets", "Plage", "Aventures"],
  },
  {
    id: 10,
    name: "Photo & Vidéo",
    icon: Camera,
    href: "photo",
    description: "Shooting photo, services vidéo et impressions.",
    count: 18,
    image:
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1200",
    subcategories: ["Studio", "Événements", "Impressions", "Drone"],
  },
  {
    id: 11,
    name: "Animaux",
    icon: PawPrint,
    href: "pets",
    description:
      "Produits et services pour animaux : toilettage, alimentation, soins.",
    count: 22,
    image:
      "https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=1200",
    subcategories: ["Toilettage", "Alimentation", "Santé", "Accessoires"],
  },
  {
    id: 12,
    name: "Bricolage & Maison",
    icon: Hammer,
    href: "home",
    description: "Outils, décorations, réparations et services maison.",
    count: 51,
    image:
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200",
    subcategories: ["Outils", "Décoration", "Plomberie", "Electricité"],
  },
  {
    id: 13,
    name: "Éducation & Cours",
    icon: GraduationCap,
    href: "education",
    description: "Formations, cours en ligne et ateliers.",
    count: 37,
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1200",
    subcategories: ["Langues", "Développement", "Art", "Entrepreneuriat"],
  },
  {
    id: 14,
    name: "Événements & Spectacles",
    icon: Music,
    href: "events",
    description: "Concerts, pièces de théâtre, spectacles et soirées.",
    count: 14,
    image:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=1200",
    subcategories: ["Concerts", "Clubbing", "Théâtre", "Cinéma"],
  },
  {
    id: 15,
    name: "Bébés & Enfants",
    icon: Baby,
    href: "kids",
    description: "Produits et activités pour bébés et enfants.",
    count: 47,
    image:
      "https://images.unsplash.com/photo-1503457574462-bd27054394c1?q=80&w=1200",
    subcategories: ["Jouets", "Vêtements", "Éveil", "Activités"],
  },
  {
    id: 16,
    name: "Nature & Plein air",
    icon: Trees,
    href: "outdoors",
    description: "Randonnée, camping, matériel outdoor et aventures.",
    count: 29,
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200",
    subcategories: ["Randonnée", "Camping", "Pêche", "Aventures"],
  },
  {
    id: 17,
    name: "Tech & Électronique",
    icon: Cpu,
    href: "tech",
    description: "Smartphones, accessoires, PC et gadgets high-tech.",
    count: 76,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200",
    subcategories: ["Smartphones", "Accessoires", "Audio", "Gaming"],
  },
];

export const mockPayments = [
  {
    id: "pay_01",
    orderId: "ORD-2025-0001",
    buyer: { id: "u_01", name: "Marie Dupont", email: "marie@example.com" },
    amount: 7500,
    currency: "XAF",
    method: "Mobile Money",
    createdAt: "2025-12-10T09:24:00.000Z",
    status: "succeeded",
  },
  {
    id: "pay_02",
    orderId: "ORD-2025-0002",
    buyer: { id: "u_02", name: "Paul Nkong", email: "paul@example.com" },
    amount: 15000,
    currency: "XAF",
    method: "Card",
    createdAt: "2025-12-11T14:02:00.000Z",
    status: "pending",
  },
  {
    id: "pay_03",
    orderId: "ORD-2025-0003",
    buyer: { id: "u_03", name: "Amina Bello", email: "amina@example.com" },
    amount: 4200,
    currency: "XAF",
    method: "Mobile Money",
    createdAt: "2025-11-30T18:40:00.000Z",
    status: "refunded",
    refundedAmount: 4200,
  },
  {
    id: "pay_04",
    orderId: "ORD-2025-0004",
    buyer: { id: "u_04", name: "Ngwa Tech", email: "ngwa@company.com" },
    amount: 30000,
    currency: "XAF",
    method: "Bank Transfer",
    createdAt: "2025-12-13T07:15:00.000Z",
    status: "failed",
  },
];

export const mockOrdersReceived = [
  {
    id: "ord_001",
    orderNumber: "CMD-2025-0001",
    dealTitle: "Dîner romantique pour 2 personnes",
    buyer: {
      id: "u_001",
      name: "Marie Dupont",
      email: "marie.dupont@email.com",
    },
    quantity: 1,
    totalAmount: 15000,
    currency: "XAF",
    status: "pending",
    createdAt: "2025-12-13T18:42:00.000Z",
  },
  {
    id: "ord_002",
    orderNumber: "CMD-2025-0002",
    dealTitle: "Massage relaxant 1h – Zen Spa",
    buyer: {
      id: "u_002",
      name: "Paul Nkong",
      email: "paul.nkong@email.com",
    },
    quantity: 2,
    totalAmount: 20000,
    currency: "XAF",
    status: "confirmed",
    createdAt: "2025-12-12T10:15:00.000Z",
  },
  {
    id: "ord_003",
    orderNumber: "CMD-2025-0003",
    dealTitle: "Abonnement Fitness – 1 mois",
    buyer: {
      id: "u_003",
      name: "Amina Bello",
      email: "amina.bello@email.com",
    },
    quantity: 1,
    totalAmount: 12000,
    currency: "XAF",
    status: "used",
    createdAt: "2025-12-10T08:30:00.000Z",
    usedAt: "2025-12-11T17:05:00.000Z",
  },
  {
    id: "ord_004",
    orderNumber: "CMD-2025-0004",
    dealTitle: "Coiffure + soin capillaire",
    buyer: {
      id: "u_004",
      name: "Ngwa Tech",
      email: "contact@ngwatech.com",
    },
    quantity: 3,
    totalAmount: 18000,
    currency: "XAF",
    status: "cancelled",
    createdAt: "2025-12-09T14:50:00.000Z",
  },
  {
    id: "ord_005",
    orderNumber: "CMD-2025-0005",
    dealTitle: "Bon shopping – 10 000 FCFA",
    buyer: {
      id: "u_005",
      name: "Junior Kamdem",
      email: "junior.kamdem@email.com",
    },
    quantity: 1,
    totalAmount: 10000,
    currency: "XAF",
    status: "refunded",
    createdAt: "2025-12-08T16:20:00.000Z",
  },
];

export const mockReviews = [
  {
    id: "rev_001",
    orderNumber: "CMD-2025-0001",
    dealTitle: "Dîner romantique pour 2 personnes",
    buyer: {
      id: "u_001",
      name: "Marie Dupont",
      email: "marie.dupont@email.com",
    },
    rating: 4.5,
    comment:
      "Très belle expérience, le repas était excellent et le service impeccable.",
    status: "published",
    createdAt: "2025-12-13T19:10:00.000Z",
  },
  {
    id: "rev_002",
    orderNumber: "CMD-2025-0002",
    dealTitle: "Massage relaxant 1h – Zen Spa",
    buyer: {
      id: "u_002",
      name: "Paul Nkong",
      email: "paul.nkong@email.com",
    },
    rating: 3,
    comment: "Bon massage mais le temps d’attente était un peu long.",
    status: "published",
    createdAt: "2025-12-12T11:40:00.000Z",
  },
  {
    id: "rev_003",
    orderNumber: "CMD-2025-0003",
    dealTitle: "Abonnement Fitness – 1 mois",
    buyer: {
      id: "u_003",
      name: "Amina Bello",
      email: "amina.bello@email.com",
    },
    rating: 5,
    comment: "Salle très propre, coachs professionnels. Je recommande à 100%.",
    status: "published",
    createdAt: "2025-12-11T09:05:00.000Z",
  },
  {
    id: "rev_004",
    orderNumber: "CMD-2025-0004",
    dealTitle: "Coiffure + soin capillaire",
    buyer: {
      id: "u_004",
      name: "Ngwa Tech",
      email: "contact@ngwatech.com",
    },
    rating: 2.5,
    comment: "Résultat correct mais pas conforme à ce qui était annoncé.",
    status: "pending",
    createdAt: "2025-12-10T15:25:00.000Z",
  },
  {
    id: "rev_005",
    orderNumber: "CMD-2025-0005",
    dealTitle: "Bon shopping – 10 000 FCFA",
    buyer: {
      id: "u_005",
      name: "Junior Kamdem",
      email: "junior.kamdem@email.com",
    },
    rating: 1,
    comment: "Très mauvaise expérience, refus du bon en magasin.",
    status: "hidden",
    createdAt: "2025-12-09T17:55:00.000Z",
  },
];
