import { Clock, Shield, TrendingDown, Users, Fish, Beef } from "lucide-react";

export const mockDeals = [
  {
    id: 1,
    title: "Bœuf Charolais Premium - 5kg",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=300&fit=crop",
    originalPrice: 120000,
    groupPrice: 75,
    unit: 150,
    sold: 45,
    total: 100,
    deadline: "10 jours",
    category: "bovins",
    city: "Douala",
    discount: 38,
    popular: true,
    status: "published",
  },
  {
    id: 2,
    title: "Tilapia Frais du Wouri - 3kg",
    image:
      "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=400&h=300&fit=crop",
    originalPrice: 18000,
    groupPrice: 12,
    unit: 150,
    sold: 82,
    total: 150,
    deadline: "3 jours",
    category: "poissons",
    city: "Douala",
    discount: 33,
    popular: false,
    status: "published",
  },
  {
    id: 3,
    title: "Viande de Bœuf Hachée - 2kg",
    image:
      "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop",
    originalPrice: 45000,
    groupPrice: 28,
    unit: 150,
    sold: 67,
    total: 120,
    deadline: "7 jours",
    category: "bovins",
    city: "Yaoundé",
    discount: 38,
    popular: false,
    status: "published",
  },
  {
    id: 4,
    title: "Saumon Frais - 2kg",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop",
    originalPrice: 65000,
    groupPrice: 42,
    unit: 150,
    sold: 34,
    total: 80,
    deadline: "2 jours",
    category: "poissons",
    city: "Douala",
    discount: 35,
    popular: false,
    status: "draft",
  },
  {
    id: 5,
    title: "Côtes de Bœuf Grillades - 4kg",
    image:
      "https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=400&h=300&fit=crop",
    originalPrice: 95000,
    groupPrice: 58,
    unit: 150,
    sold: 28,
    total: 100,
    deadline: "14 jours",
    category: "bovins",
    city: "Douala",
    discount: 39,
    popular: false,
    status: "published",
  },
  {
    id: 6,
    title: "Crevettes Géantes - 1.5kg",
    image:
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop",
    originalPrice: 48000,
    groupPrice: 29,
    unit: 150,
    sold: 91,
    total: 150,
    deadline: "4 jours",
    category: "poissons",
    city: "Kribi",
    discount: 40,
    popular: true,
    status: "published",
  },
  {
    id: 7,
    title: "Entrecôte de Bœuf Premium - 3kg",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop",
    originalPrice: 78000,
    groupPrice: 49,
    unit: 150,
    sold: 55,
    total: 100,
    deadline: "9 jours",
    category: "bovins",
    city: "Yaoundé",
    discount: 37,
    popular: false,
    status: "published",
  },
  {
    id: 8,
    title: "Bar Sauvage Entier - 2.5kg",
    image:
      "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=400&h=300&fit=crop",
    originalPrice: 38000,
    groupPrice: 23,
    unit: 150,
    sold: 71,
    total: 120,
    deadline: "5 jours",
    category: "poissons",
    city: "Douala",
    discount: 39,
    popular: false,
    status: "published",
  },
];
export const features = [
  {
    icon: Users,
    title: "Force du Groupe",
    description: "Plus vous êtes nombreux, plus la réduction est importante",
  },
  {
    icon: TrendingDown,
    title: "Économies Garanties",
    description: "Jusqu'à 70% de réduction sur les meilleurs deals",
  },
  {
    icon: Clock,
    title: "Délais Courts",
    description:
      "Les deals disparaissent rapidement. Saisissez l'opportunité !",
  },
  {
    icon: Shield,
    title: "Sécurisé",
    description: "Paiement sécurisé et garantie de satisfaction client",
  },
];

export const slides = [
  {
    id: 1,
    title: "Découvrez les Meilleurs Deals",
    subtitle: "Jusqu'à 70% de réduction",
    description:
      "Restaurants, spa, activités et bien plus encore dans votre ville",
    buttonText: "Explorer maintenant",
    buttonLink: "/deals",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    gradient: "from-purple-600/50 to-pink-600/50",
    textColor: "text-white",
    badge: "Nouveauté",
  },
  {
    id: 2,
    title: "Bien-être & Détente",
    subtitle: "Offres exclusives Spa",
    description:
      "Profitez d'un moment de relaxation avec nos offres spa et massage",
    buttonText: "Voir les offres spa",
    buttonLink: "/deals/spa",
    image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80",
    gradient: "from-teal-600/50 to-cyan-600/50",
    textColor: "text-white",
    badge: "Populaire",
  },
  {
    id: 3,
    title: "Saveurs Gastronomiques",
    subtitle: "Restaurants étoilés à prix réduits",
    description:
      "Découvrez les meilleurs restaurants de votre ville à des prix imbattables",
    buttonText: "Réserver une table",
    buttonLink: "/deals/restaurants",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    gradient: "from-orange-600/50 to-red-600/50",
    textColor: "text-white",
    badge: "Tendance",
  },
  {
    id: 4,
    title: "Activités & Loisirs",
    subtitle: "Vivez des expériences uniques",
    description:
      "Sport, culture, aventure... Trouvez l'activité qui vous correspond",
    buttonText: "Découvrir les activités",
    buttonLink: "/deals/activities",
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&q=80",
    gradient: "from-blue-600/50 to-indigo-600/50",
    textColor: "text-white",
    badge: "Aventure",
  },
];

export const categories = [
  {
    id: 1,
    name: "Poissons",
    icon: Fish,
    href: "poissons",
    slug: "poissons",
    description:
      "Découvrez des offres exclusives sur les meilleurs poissons près de chez vous.",
    count: 124,
    isActive: true,
    image:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1200",
    subcategories: ["Cuisine africaine", "Fast-food", "Desserts", "Buffets"],
  },
  {
    id: 2,
    name: "Bovins",
    icon: Beef,
    href: "bovins",
    slug: "bovins",
    isActive: true,
    description:
      "Découvrez des offres exclusives sur les meilleurs bovins près de chez vous.",
    count: 89,
    image:
      "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?q=80&w=1200",
    subcategories: ["Massages", "Coiffure", "Soins du visage", "Manicure"],
  },
];

export const mockPayments = [
  {
    id: "pay_01",
    orderId: "ORD-2025-0001",
    buyer: { id: "u_01", name: "Marie Dupont", email: "marie@example.com" },
    amount: 7500,
    currency: "USD",
    method: "Mobile Money",
    createdAt: "2025-12-10T09:24:00.000Z",
    status: "succeeded",
  },
  {
    id: "pay_02",
    orderId: "ORD-2025-0002",
    buyer: { id: "u_02", name: "Paul Nkong", email: "paul@example.com" },
    amount: 15000,
    currency: "USD",
    method: "Card",
    createdAt: "2025-12-11T14:02:00.000Z",
    status: "pending",
  },
  {
    id: "pay_03",
    orderId: "ORD-2025-0003",
    buyer: { id: "u_03", name: "Amina Bello", email: "amina@example.com" },
    amount: 4200,
    currency: "USD",
    method: "Mobile Money",
    createdAt: "2025-11-30T18:40:00.000Z",
    status: "refunded",
    refundedAmount: 4200,
  },
  {
    id: "pay_04",
    orderId: "ORD-2025-0004",
    buyer: { id: "u_04", name: "Ngwa Tech", email: "ngwa@company.com" },
    amount: 30000,
    currency: "USD",
    method: "Bank Transfer",
    createdAt: "2025-12-13T07:15:00.000Z",
    status: "failed",
  },
];

export const mockOrdersReceived = [
  {
    id: "ord_001",
    orderNumber: "CMD-2025-0001",
    dealTitle: "Dîner romantique pour 2 personnes",
    buyer: {
      id: "u_001",
      name: "Marie Dupont",
      email: "marie.dupont@email.com",
    },
    quantity: 1,
    totalAmount: 15000,
    currency: "USD",
    status: "pending",
    createdAt: "2025-12-13T18:42:00.000Z",
  },
  {
    id: "ord_002",
    orderNumber: "CMD-2025-0002",
    dealTitle: "Massage relaxant 1h – Zen Spa",
    buyer: {
      id: "u_002",
      name: "Paul Nkong",
      email: "paul.nkong@email.com",
    },
    quantity: 2,
    totalAmount: 20000,
    currency: "USD",
    status: "confirmed",
    createdAt: "2025-12-12T10:15:00.000Z",
  },
  {
    id: "ord_003",
    orderNumber: "CMD-2025-0003",
    dealTitle: "Abonnement Fitness – 1 mois",
    buyer: {
      id: "u_003",
      name: "Amina Bello",
      email: "amina.bello@email.com",
    },
    quantity: 1,
    totalAmount: 12000,
    currency: "USD",
    status: "used",
    createdAt: "2025-12-10T08:30:00.000Z",
    usedAt: "2025-12-11T17:05:00.000Z",
  },
  {
    id: "ord_004",
    orderNumber: "CMD-2025-0004",
    dealTitle: "Coiffure + soin capillaire",
    buyer: {
      id: "u_004",
      name: "Ngwa Tech",
      email: "contact@ngwatech.com",
    },
    quantity: 3,
    totalAmount: 18000,
    currency: "USD",
    status: "cancelled",
    createdAt: "2025-12-09T14:50:00.000Z",
  },
  {
    id: "ord_005",
    orderNumber: "CMD-2025-0005",
    dealTitle: "Bon shopping – 10 000 $",
    buyer: {
      id: "u_005",
      name: "Junior Kamdem",
      email: "junior.kamdem@email.com",
    },
    quantity: 1,
    totalAmount: 10000,
    currency: "USD",
    status: "refunded",
    createdAt: "2025-12-08T16:20:00.000Z",
  },
];

export const mockReviews = [
  {
    id: "rev_001",
    orderNumber: "CMD-2025-0001",
    dealTitle: "Tilapia Frais du Wouri - 3kg",
    buyer: {
      id: "u_001",
      name: "Marie Essomba",
      email: "marie.essomba@email.com",
    },
    rating: 5,
    comment:
      "Poisson très frais, livraison rapide. Parfait pour notre repas de famille. Je recommande vivement!",
    status: "published",
    createdAt: "2025-12-13T19:10:00.000Z",
  },
  {
    id: "rev_002",
    orderNumber: "CMD-2025-0002",
    dealTitle: "Viande de Bœuf Hachée - 2kg",
    buyer: {
      id: "u_002",
      name: "Paul Nkong",
      email: "paul.nkong@email.com",
    },
    rating: 4,
    comment:
      "Bonne qualité de viande, bien emballée. Juste un peu de retard à la livraison.",
    status: "published",
    createdAt: "2025-12-12T11:40:00.000Z",
  },
  {
    id: "rev_003",
    orderNumber: "CMD-2025-0003",
    dealTitle: "Crevettes Géantes - 1.5kg",
    buyer: {
      id: "u_003",
      name: "Amina Bello",
      email: "amina.bello@email.com",
    },
    rating: 5,
    comment:
      "Excellentes crevettes, bien calibrées et ultra fraîches. Le prix groupé est imbattable!",
    status: "published",
    createdAt: "2025-12-11T09:05:00.000Z",
  },
  {
    id: "rev_004",
    orderNumber: "CMD-2025-0004",
    dealTitle: "Entrecôte de Bœuf Premium - 3kg",
    buyer: {
      id: "u_004",
      name: "Jean Fotso",
      email: "jean.fotso@email.com",
    },
    rating: 3.5,
    comment:
      "Viande correcte mais pas aussi tendre que je l'espérais. Le goût reste bon.",
    status: "pending",
    createdAt: "2025-12-10T15:25:00.000Z",
  },
  {
    id: "rev_005",
    orderNumber: "CMD-2025-0005",
    dealTitle: "Maquereau Fumé - 4kg",
    buyer: {
      id: "u_005",
      name: "Junior Kamdem",
      email: "junior.kamdem@email.com",
    },
    rating: 4.5,
    comment:
      "Très bon poisson fumé, bien préparé. Idéal pour les repas en famille. Bon rapport qualité-prix.",
    status: "published",
    createdAt: "2025-12-09T17:55:00.000Z",
  },
  {
    id: "rev_006",
    orderNumber: "CMD-2025-0006",
    dealTitle: "Bar Sauvage Entier - 2.5kg",
    buyer: {
      id: "u_006",
      name: "Charlotte Mbida",
      email: "charlotte.mbida@email.com",
    },
    rating: 5,
    comment:
      "Poisson d'une fraîcheur exceptionnelle! Parfait pour notre grillade. Merci!",
    status: "published",
    createdAt: "2025-12-08T14:30:00.000Z",
  },
  {
    id: "rev_007",
    orderNumber: "CMD-2025-0007",
    dealTitle: "Côtes de Bœuf Grillades - 4kg",
    buyer: {
      id: "u_007",
      name: "Rodrigue Tagne",
      email: "rodrigue.tagne@email.com",
    },
    rating: 2.5,
    comment:
      "Viande moins tendre que prévu, beaucoup de gras. Déçu du rapport qualité-prix.",
    status: "hidden",
    createdAt: "2025-12-07T10:15:00.000Z",
  },
  {
    id: "rev_008",
    orderNumber: "CMD-2025-0008",
    dealTitle: "Saumon Frais - 2kg",
    buyer: {
      id: "u_008",
      name: "Sylvie Ekotto",
      email: "sylvie.ekotto@email.com",
    },
    rating: 4.5,
    comment:
      "Saumon de très belle qualité, bien frais. Un peu cher même avec la réduction mais ça vaut le coup.",
    status: "published",
    createdAt: "2025-12-06T16:45:00.000Z",
  },
  {
    id: "rev_009",
    orderNumber: "CMD-2025-0009",
    dealTitle: "Bœuf Charolais Premium - 5kg",
    buyer: {
      id: "u_009",
      name: "Emmanuel Tchuente",
      email: "emmanuel.tchuente@email.com",
    },
    rating: 5,
    comment:
      "Viande exceptionnelle! Très tendre et savoureuse. Parfait pour notre barbecue. Je recommande!",
    status: "published",
    createdAt: "2025-12-05T12:20:00.000Z",
  },
  {
    id: "rev_010",
    orderNumber: "CMD-2025-0010",
    dealTitle: "Bœuf Bourguignon - Pack 6kg",
    buyer: {
      id: "u_010",
      name: "Grace Nguetsop",
      email: "grace.nguetsop@email.com",
    },
    rating: 3,
    comment:
      "Viande convenable pour mijoter mais quelques morceaux nerveux. Livraison ok.",
    status: "pending",
    createdAt: "2025-12-04T08:50:00.000Z",
  },
];

export const popularDeals = [
  {
    id: 2,
    title: "Tilapia Frais du Wouri - 3kg",
    image: "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=400",
    originalPrice: 18000,
    groupPrice: 12,
    unit: 150,
    sold: 82,
    total: 150,
    deadline: "3 jours",
    category: "poissons",
    city: "Douala",
    discount: 33,
    popular: true,
  },
  {
    id: 10,
    title: "Maquereau Fumé - 4kg",
    image: "https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=400",
    originalPrice: 25000,
    groupPrice: 16,
    unit: 150,
    sold: 103,
    total: 150,
    deadline: "6 jours",
    category: "poissons",
    city: "Limbé",
    discount: 36,
    popular: true,
  },
  {
    id: 6,
    title: "Crevettes Géantes - 1.5kg",
    image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400",
    originalPrice: 48000,
    groupPrice: 29,
    unit: 150,
    sold: 91,
    total: 150,
    deadline: "4 jours",
    category: "poissons",
    city: "Kribi",
    discount: 40,
    popular: true,
  },
  {
    id: 8,
    title: "Bar Sauvage Entier - 2.5kg",
    image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=400",
    originalPrice: 38000,
    groupPrice: 23,
    unit: 150,
    sold: 71,
    total: 120,
    deadline: "5 jours",
    category: "poissons",
    city: "Douala",
    discount: 39,
    popular: true,
  },
  {
    id: 3,
    title: "Viande de Bœuf Hachée - 2kg",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400",
    originalPrice: 45000,
    groupPrice: 28,
    unit: 150,
    sold: 67,
    total: 120,
    deadline: "7 jours",
    category: "bovins",
    city: "Yaoundé",
    discount: 38,
    popular: true,
  },
  {
    id: 5,
    title: "Entrecôte de Bœuf Premium - 3kg",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400",
    originalPrice: 78000,
    groupPrice: 49,
    unit: 150,
    sold: 55,
    total: 100,
    deadline: "9 jours",
    category: "bovins",
    city: "Yaoundé",
    discount: 37,
    popular: true,
  },
];

export const mockMerchants = [
  {
    id: "1",
    name: "Restaurant Le Gourmet",
    email: "contact@legourmet.cm",
    phone: "+237 6 90 00 00 01",
    totalDeals: 12,
    totalSales: 450000,
    status: "active",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Spa Wellness",
    email: "info@spawellness.cm",
    phone: "+237 6 90 00 00 02",
    totalDeals: 8,
    totalSales: 280000,
    status: "active",
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    name: "Boutique Mode",
    email: "contact@boutiquemode.cm",
    phone: "+237 6 90 00 00 03",
    totalDeals: 5,
    totalSales: 150000,
    status: "pending",
    createdAt: "2024-03-10",
  },
  {
    id: "4",
    name: "Auto Service Pro",
    email: "service@autopro.cm",
    phone: "+237 6 90 00 00 04",
    totalDeals: 3,
    totalSales: 95000,
    status: "suspended",
    createdAt: "2024-03-25",
  },
];
