apiVersion: v1
kind: Secret
metadata:
  name: bff-secret
  namespace: paytogether
type: Opaque
stringData:

  # -------------------------------------------------------
  # Base de données
  # -------------------------------------------------------
  DB_PASSWORD: "ZhKdrpgibRkzWodAw6rRABraPdXRcbpW"

  # -------------------------------------------------------
  # JWT
  # -------------------------------------------------------
  JWT_SECRET: "monSecretSuperSecurisePourPayTogether2024!"

  # -------------------------------------------------------
  # API Auth (Keycloak)
  # -------------------------------------------------------
  API_AUTH_KEY: "votre-cle-api-auth"
  API_AUTH_ADMIN_PASSWORD: "$2a$10$ZCfYq7kvNvLsuUKmzDWkjebC2QozV9L8whpF6n85BGwtBFABEuD62"

  # -------------------------------------------------------
  # MinIO
  # -------------------------------------------------------
  MINIO_ACCESS_NAME: "ulrichAfric"
  MINIO_ACCESS_SECRET: "ulrSms@Afric"

  # -------------------------------------------------------
  # Square Payment
  # -------------------------------------------------------
  SQUARE_ACCESS_TOKEN: "EAAAlzEGRN5icWUbx_jZpcwCStCKIyusp1RkkgAEbH822aEO2UWkGmSufogLHnpK"
  SQUARE_LOCATION_ID: "LCWBGZWCNNH4D"

  # -------------------------------------------------------
  # Redis Cache
  # -------------------------------------------------------
  REDIS_PASSWORD: ""
