import { Clock, Shield, TrendingDown, Users } from "lucide-react";

export const mockDeals = [
  {
    id: 1,
    title: "Massage Premium Spa",
    image: "/spa-massage-luxe.jpg",
    originalPrice: 150,
    groupPrice: 75,
    unit: "séance",
    sold: 42,
    total: 100,
    deadline: "15 jours",
    category: "wellness",
    city: "Paris",
    discount: 50,
  },
  {
    id: 2,
    title: "Restaurant Gastronomique",
    image: "/restaurant-gastronomique-diner.jpg",
    originalPrice: 85,
    groupPrice: 49,
    unit: "menu",
    sold: 78,
    total: 150,
    deadline: "8 jours",
    category: "food",
    city: "Lyon",
    discount: 42,
  },
  {
    id: 3,
    title: "Cours de Yoga",
    image: "/yoga-course-wellness.jpg",
    originalPrice: 40,
    groupPrice: 24,
    unit: "mois",
    sold: 25,
    total: 50,
    deadline: "22 jours",
    category: "wellness",
    city: "Marseille",
    discount: 40,
  },
  {
    id: 4,
    title: "Gadgets Tech Premium",
    image: "/tech-gadgets-electronics.jpg",
    originalPrice: 199,
    groupPrice: 129,
    unit: "unité",
    sold: 156,
    total: 200,
    deadline: "5 jours",
    category: "tech",
    city: "Paris",
    discount: 35,
  },
  {
    id: 5,
    title: "Formation Digital Marketing",
    image: "/digital-marketing-training.jpg",
    originalPrice: 299,
    groupPrice: 149,
    unit: "cours",
    sold: 33,
    total: 100,
    deadline: "18 jours",
    category: "education",
    city: "Toulouse",
    discount: 50,
  },
  {
    id: 6,
    title: "Accessoires Fashion",
    image: "/fashion-accessories-luxury.jpg",
    originalPrice: 120,
    groupPrice: 59,
    unit: "article",
    sold: 89,
    total: 120,
    deadline: "12 jours",
    category: "fashion",
    city: "Bordeaux",
    discount: 51,
  },
];

export const features = [
  {
    icon: Users,
    title: "Force du Groupe",
    description: "Plus vous êtes nombreux, plus la réduction est importante",
  },
  {
    icon: TrendingDown,
    title: "Économies Garanties",
    description: "Jusqu'à 70% de réduction sur les meilleurs deals",
  },
  {
    icon: Clock,
    title: "Délais Courts",
    description:
      "Les deals disparaissent rapidement. Saisissez l'opportunité !",
  },
  {
    icon: Shield,
    title: "Sécurisé",
    description: "Paiement sécurisé et garantie de satisfaction client",
  },
];
